### ISSUE TITLE
Replicating mptcp -> connection fail error

### ISSUE THREAD

**Issue by Haxwell1** [ramonfontes/reproducible-research#16]
I am trying to replicate your Mptcp code using the manual https://usermanual.wiki/Pdf/mininetwifidraftmanual.297704656/view at 7.5.2. 

However, when reaching the step of "Node: sta1 (terminal2)$iperf -c 192.168.1.254" i get an error stating: "Connection failed: Network unreachable". 

Why is this, what have I missed?

**Comment by ramonfontes** [comment]
Are you using the kernel created by MPTCP?

**Comment by Haxwell1** [comment]
I am not sure, but i think not? Is it something special i need to do to start the kernel? I am running on a VM in virtualbox FYI.

**Comment by ramonfontes** [comment]
If you have installed MPTCP a new kernel has been created for you.

**Comment by Haxwell1** [comment]
I have installed MPTCP following: https://multipath-tcp.org/pmwiki.php/Users/AptRepository. However not done their configure routing part. So if i am not supposed to perform any specific command to run the MPTCP kernel, why am i getting the error?

**Comment by ramonfontes** [comment]
Dear, 

Yoi have to boot your system with the MPTCP kernel.

**Comment by Haxwell1** [comment]
My bad, now i understand. I have now booted from mptcp kernel and i still get the same error message.

**Comment by ramonfontes** [comment]
Please make sure that sta1's route table is correctly configured.

**Comment by Haxwell1** [comment]
ok, I am quite new to all of this as you probably understand and I have used the code provided by you in https://github.com/ramonfontes/reproducible-research/blob/master/mininet-wifi/The-Computer-Journal-2017/mptcp.py. What you mean is that in the lines of code stating:

sta1.cmd('ifconfig sta1-wlan0 10.0.0.10/8')
    sta1.cmd('ifconfig sta1-wlan1 192.168.0.10/24')

    sta1.cmd('ip route add default 10.0.0.254/8 via sta1-wlan0')
    sta1.cmd('ip route add default 192.168.0.254/24 via sta1-wlan1')

    sta1.cmd('ip rule add from 10.0.0.10 table 1')
    sta1.cmd('ip rule add from 192.168.0.10 table 2')

    sta1.cmd('ip route add 10.0.0.0 dev sta1-wlan0 scope link table 1')
    sta1.cmd('ip route add default via 10.0.0.254 dev sta1-wlan0 table 1')

    sta1.cmd('ip route add 192.168.0.0 dev sta1-wlan1 scope link table 2')
    sta1.cmd('ip route add default via 192.168.0.254 dev sta1-wlan1 table 2')

    sta1.cmd('ip route add default scope global nexthop via 10.0.0.254 dev sta1-wlan0')

These should be changed? And sorry but to what, or how do I find out? I am so sorry for what must be very low level questions to you, but i am writing a thesis about MPTCP and all help is much appreciated!

**Comment by ramonfontes** [comment]
My question is about computer networking basics. :( Could you please check whether `sta1` has some default gateway? Could you also confirm that `sta1` is connected to `ap2` and `ap3`?

**Comment by ramonfontes** [comment]
Please try the new `mptcp.py` file and let me know the result.

I've also added a README file: https://github.com/ramonfontes/reproducible-research/tree/master/mininet-wifi/The-Computer-Journal-2017

**Comment by Haxwell1** [comment]
I get the following error when running sudo python mptcp.py command:

*** Creating nodes
Connecting to remote controller at 127.0.0.1:6653
*** Configuring wifi nodes
command failed: No such file or directory (-2)
command failed: No such file or directory (-2)
Error: Please run sudo mn -c.
Error: Please run sudo mn -c.
*** Associating and Creating links
*** Error: Cannot find device "sta1-wlan1"
*** Error: Cannot find device "sta1-wlan1"
*** Error: Cannot find device "sta1-wlan1"
Traceback (most recent call last):
  File "mptcp.py", line 106, in <module>
    topology()
  File "mptcp.py", line 51, in topology
    net.addLink(ap3, sta1, 0, 2)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.5-py2.7.egg/mn_wifi/net.py", line 583, in addLink
    self.infra_tc(node1, node2, port1, port2, cls, **params)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.5-py2.7.egg/mn_wifi/net.py", line 525, in infra_tc
    intf, ap_intf = self.get_intf(node1, node2, port1, port2)
  File "/usr/local/lib/python2.7/dist-packages/mininet_wifi-2.5-py2.7.egg/mn_wifi/net.py", line 508, in get_intf
    intf = sta.wintfs[wlan]
KeyError: 2

**Comment by ramonfontes** [comment]
Did you try `sudo mn -c`??

**Comment by Haxwell1** [comment]
Yes i tried the sudo mn -c, but the change to addLink helped.

However, i still get the same error: "connect failed: Network is unreachable"

**Comment by ramonfontes** [comment]
What about the default gateway? You have not confirmed whether `sta1` is connected to the APs too. Please provide as much information as you can. Otherwise, I won't be able to help you.

**Comment by Haxwell1** [comment]
I get the following output in the mininet terminal so as I can see sta1 is connected to both ap2 and ap3 through sta1-wlan0 and sta1-wlan1 respectivelly.

mininet-wifi> sta1 iw dev sta1-wlan0 link
Connected to 00:00:00:00:00:02 (on sta1-wlan0)
	SSID: ssid_ap2
	freq: 2437
	RX: 443933 bytes (9964 packets)
	TX: 2915 bytes (30 packets)
	signal: -30 dBm
	tx bitrate: 48.0 MBit/s

	bss flags:	short-slot-time
	dtim period:	2
	beacon int:	100
mininet-wifi> sta1 iw dev sta1-wlan1 link
Connected to 00:00:00:00:00:03 (on sta1-wlan1)
	SSID: ssid_ap3
	freq: 2412
	RX: 847918 bytes (10201 packets)
	TX: 2951 bytes (32 packets)
	signal: -30 dBm
	tx bitrate: 65.0 MBit/s MCS 7

	bss flags:	short-slot-time
	dtim period:	2
	beacon int:	100

**Comment by ramonfontes** [comment]
Two default gateways are defined in [L75](https://github.com/ramonfontes/reproducible-research/blob/master/mininet-wifi/The-Computer-Journal-2017/mptcp.py#L75) and [L78](https://github.com/ramonfontes/reproducible-research/blob/master/mininet-wifi/The-Computer-Journal-2017/mptcp.py#L78). So please run your code in debug level and see what is going wrong with these lines when you run the code.

You should observe something like below:

```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.0.254      0.0.0.0         UG    0      0        0 sta1-wlan0
....
```

**Comment by Haxwell1** [comment]
Ok i been trying to debug but i don't know what is going wrong. Isn't there any way to perform the routing during runtime?

**Comment by ramonfontes** [comment]
Of course. By running the command manually.
